Bitloops install
bitloops/bitloops-workflow pull request #9
Opened 2022-03-23 14:24 UTC by Varagos

2022-04-13 14:03 UTC, sardounis commented on README.md
> +_Create and update strongly-typed HTTP/2 REST APIs in seconds and use them instantly as RPCs on your client code with just a single line of code_
It seems here is an unnecessary duplication.

2022-04-13 14:03 UTC, sardounis commented on README.md
> +_Create and update strongly-typed HTTP/2 REST APIs in seconds and use them instantly as RPCs on your client code with just a single line of code_
It seems here is an unnecessary duplication.

2022-04-15 14:37 UTC, danias commented on docs/Install.md
> +    "workspaceId": "db24bb48-d2e3-4433-8fd0-79eef2bf63df"
Remove our workspaceId

2022-04-15 14:40 UTC, danias requested changes

2022-04-15 14:40 UTC, danias commented on docs/Install.md
> +Follow [ngrok setup](https://dashboard.ngrok.com/get-started/setup), run this next
Remove ngrok

2022-04-15 14:40 UTC, danias commented on mongo-seed/environments.json
> +    "workspaceId": "db24bb48-d2e3-4433-8fd0-79eef2bf63df"
remove

2022-04-15 14:42 UTC, danias approved these changes, later dismissed

2022-04-15 14:44 UTC, danias approved these changes

2022-04-15 14:45 UTC, merged